name: 'Create Tags From'
description: 'Auto create tags from commit or package.json.'
author: 'Kenny Wong'
inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true

  version:
    description: 'Create tag for specified version'
    default: ''
    required: false

  test:
    description: 'The regular expression matches the submitted content.'
    default: ''
    required: false

  package-path:
    description: 'The path of the package.json file.'
    default: ''
    required: false

outputs:
  version:
    description: 'The version number of the tag created. example: v1.0.0'
  majorVersion:
    description: 'MAJOR version when you make incompatible API changes.'
  minorVersion:
    description: 'MINOR version when you add functionality in a backwards compatible manner, and.'
  patchVersion:
    description: 'PATCH version when you make backwards compatible bug fixes.'
  versionNumber:
    description: 'The version number of the tag created. example: 1.0.0'
  preversion:
    description: 'The previous tag version number.'
  preversionNumber:
    description: 'The previous tag version number of the tag created. example: v1.0.0'
  successful:
    description: 'The tag was successfully created.'
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'tag'
  color: 'black'