name: 'Create Tags From'
description: 'Auto create tags from commit or package.json.'
author: 'Kenny Wong'
inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true

  package-path:
    description: 'The path of the package.json file.'
    default: ''
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
