name: 'Create Tags From'
description: 'Auto create tags from commit or package.json.'
author: 'Kenny Wong'
inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
