name: 'Create Tags from commit'
description: 'Auto create tags from commit.'
author: 'Kenny Wong'
inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
