name: 'Create Tags From'
description: 'Auto create tags from commit or package.json.'
author: 'Kenny Wong'
inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true

  version:
    description: 'Create tag for specified version'
    default: ''
    required: false

  test:
    description: 'The regular expression matches the submitted content.'
    default: ''
    required: false

  package-path:
    description: 'The path of the package.json file.'
    default: ''
    required: false

outputs:
  version:
    description: 'The version number of the tag created.'
  preversion:
    description: 'The previous tag version number.'
  successful:
    description: 'The tag was successfully created.'
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'tag'
  color: 'black'