name: Create Tag
on: [push]

jobs: 
  tags: 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: npm run all

      - name: Look Changelog
        uses: jaywcjlove/changelog-generator@v1.3.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
      - run: ls -al
      - run: pwd
      - name: Is a tag created auto?
        id: create_tag
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json

      - name: The version of the tag created.
        run: echo "${{ steps.create_tag.outputs.version }}"

      - name: The version number of the tag created.
        run: echo "${{ steps.create_tag.outputs.versionNumber }}"

      - name: The MAJOR version number of the tag created.
        run: echo "${{ steps.create_tag.outputs.majorVersion }}"

      - name: The MINOR version number of the tag created.
        run: echo "${{ steps.create_tag.outputs.minorVersion }}"

      - name: The PATCH version number of the tag created.
        run: echo "${{ steps.create_tag.outputs.patchVersion }}"

      - name: The previous tag version number.
        run: echo "${{ steps.create_tag.outputs.preversion }}"

      - name: The tag was successfully created.
        run: echo "${{ steps.create_tag.outputs.successful }}"

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.3.9
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: steps.create_tag.outputs.successful
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.compareurl }}
            ```yml
            - name: Create Tags From
              uses: jaywcjlove/create-tag-action@${{ steps.create_tag.outputs.version }}
              with:
                token: # Your GITHUB_TOKEN
                test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
                # package-path: ./package.json
            ```
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
