name: CI
on: 
  push:
    branches:
      - main

jobs: 
  tags: 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: npm run all

      - run: mkdir -p build

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          output: build/index.html
          github-corners: https://github.com/jaywcjlove/create-tag-action
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏷️</text></svg>

      - run: ls -al
      - run: pwd
      - name: (test) Is a tag/release created auto? 
        uses: ./
        with:
          version: '1.3.9'
      - name: Is a tag/release created auto? 
        id: create_tag
        uses: ./
        with:
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@v1.5.0

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.5.0
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - run: echo "version - ${{ steps.create_tag.outputs.version }}"
      - run: echo "preversion - ${{ steps.create_tag.outputs.preversion }}"
      - run: echo "versionNumber - ${{ steps.create_tag.outputs.versionNumber }}"
      - run: echo "versionNumber - ${{ steps.create_tag.outputs.versionNumber }}"
      - run: echo "preversionNumber - ${{ steps.create_tag.outputs.preversionNumber }}"
      - run: echo "majorVersion - ${{ steps.create_tag.outputs.majorVersion }}"
      - run: echo "minorVersion - ${{ steps.create_tag.outputs.minorVersion }}"
      - run: echo "patchVersion - ${{ steps.create_tag.outputs.patchVersion }}"
      - run: echo "preversion - ${{ steps.create_tag.outputs.preversion }}"
      - run: echo "successful - ${{ steps.create_tag.outputs.successful }}"
      - run: echo "compareurl - ${{ steps.changelog.outputs.compareurl }}"
      - name: if ....
        if: steps.create_tag.outputs.successful
        run: echo "⚠️ successful - ${{ steps.create_tag.outputs.successful }}"

      - name: Create Release
        uses: ./
        with:
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json
          release: true
          body: |
            
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/create-tag-action/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }} 

            ```yml
            - name: Create Tags From
              uses: jaywcjlove/create-tag-action@${{ steps.create_tag.outputs.version }}
              with:
                token: # Your GITHUB_TOKEN
                test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
                # package-path: ./package.json
            ```

            ${{ steps.changelog.outputs.changelog }}

      # - name: Create Release
      #   uses: ncipollo/release-action@v1
      #   if: steps.create_tag.outputs.successful
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     name: ${{ steps.create_tag.outputs.version }}
      #     tag: ${{ steps.create_tag.outputs.version }}
      #     body: |
      #       ${{ steps.changelog.outputs.compareurl }}

      #       ```yml
      #       - name: Create Tags From
      #         uses: jaywcjlove/create-tag-action@${{ steps.create_tag.outputs.version }}
      #         with:
      #           token: # Your GITHUB_TOKEN
      #           test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
      #           # package-path: ./package.json
      #       ```

      #       ${{ steps.changelog.outputs.changelog }}

      - run: echo "changelog -> ${{ steps.changelog.outputs.tag }}"
      - run: echo "changelog -> ${{ steps.changelog.outputs.version }}"
      - run: echo "changelog -> ${{ steps.changelog.outputs.branch }}"
    outputs:
      version: ${{ steps.changelog.outputs.version }}
      tag: ${{ steps.changelog.outputs.tag }}
      successful: ${{steps.create_tag.outputs.successful }}

  test: 
    needs: [tags]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "successful - ${{ needs.tags.outputs.version }}"
      - run: echo "compareurl - ${{ needs.tags.outputs.tag }}"
      - name: if ....
        if: needs.tags.outputs.successful
        run: echo "⚠️ successful - ${{ needs.tags.outputs.successful }}"
