name: Create Tag
on: [push]

jobs: 
  tags: 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: npm run all

      - name: Look Changelog
        uses: jaywcjlove/changelog-generator@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
      - run: ls -al
      - run: pwd
      - name: Is a tag created auto?
        id: create_tag
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json

      - run: echo "version - ${{ steps.create_tag.outputs.version }}"
      - run: echo "version | preversion - ${{ steps.create_tag.outputs.version | steps.create_tag.outputs.preversion }}"
      - run: echo "versionNumber - ${{ steps.create_tag.outputs.versionNumber }}"
      - run: echo "majorVersion - ${{ steps.create_tag.outputs.majorVersion }}"
      - run: echo "minorVersion - ${{ steps.create_tag.outputs.minorVersion }}"
      - run: echo "patchVersion - ${{ steps.create_tag.outputs.patchVersion }}"
      - run: echo "preversion - ${{ steps.create_tag.outputs.preversion }}"
      - run: echo "successful - ${{ steps.create_tag.outputs.successful }}"

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - run: echo "changelog -> ${{ steps.changelog.outputs.tag }}"
      - run: echo "changelog -> ${{ steps.changelog.outputs.version }}"
      - run: echo "changelog -> ${{ steps.changelog.outputs.branch }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: steps.create_tag.outputs.successful
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.compareurl }}
            ```yml
            - name: Create Tags From
              uses: jaywcjlove/create-tag-action@${{ steps.create_tag.outputs.version }}
              with:
                token: # Your GITHUB_TOKEN
                test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
                # package-path: ./package.json
            ```
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
